### ISSUE TITLE
SPIDER_IMU : Pololu MinIMU-9 -vs- MPU9250

### ISSUE THREAD

**Issue by patrickpoirier51** [erlerobot/ros_erle_spider#4]
Erle is offering the spider on a Erle-Brain2  that is using the MPU9250
https://github.com/erlerobot/erle-brain-2-imu/blob/master/MPU9250.py

I cant figure out how you can make the MPU9250 running with this code 
https://github.com/erlerobot/ros_erle_spider/tree/master/spider_code/spider_imu/src/IMU
that relates to Pololu MinIMU-9 , as originaly developped  by Author: tuuzdu

Question: Is the Erle_Spider being shipped with a Pololu MinIMU-9 , or there is a different source for the MPU9250 that is not available ?

**Comment by vmayoral** [comment]
Hi @patrickpoirier51,
You're right the code listed makes use of the MinIMU-9. You can bring up this capability when using Erle-Brain 2 by using a modified version of https://github.com/erlerobot/ros_erle_imu. I believe that that code hasn't been made public yet.

**Comment by patrickpoirier51** [comment]
Hello Victor,
Yes I know this code, that is the one I actually used to test the mpu9250 with the RPI2 and ROS.
But I could not relate this code with the Spider_imu...  it does subscribe to BodyCommand and advertise to BodyState:
spider_code/spider_imu/src/imu_control.cpp
	body_cmd_sub = node.subscribe<spider_msgs::BodyCommand>("/teleop/body_command", 1, teleopBodyCmd);
	move_body_pub = node.advertise<spider_msgs::BodyState>("/teleop/move_body",1);

On ros_erle_imu, there is no subsriber and the 9250 is Publishing this:
ros: :Publisher imu_pub = n.advertise<sensor_msgs::Imu>("imu9250", 1000);

So correct me if I am wrong but, for the moment I can either rewrite the code to make it work with the MPU9250, or simply get a MinIMU-9 ?

**Comment by patrickpoirier51** [comment]
OK I think I get it now:


Imu_control::Imu_control(){

	body_cmd_sub = node.subscribe("/teleop/body_command", 1, &Imu_control::teleopBodyCmd, this);//No probado
	move_body_pub = node.advertise<spider_msgs::BodyState>("/teleop/move_body",1);//No probado
	pxf_imu_sub = node.subscribe("apm_inertial_sensor", 100, &Imu_control::imuCallback, this);
	ROS_INFO("Spider_imu_dev is ready...");

**Comment by patrickpoirier51** [comment]
OK I see that under: spider_code/spider_imu_dev/src/Imu_control.cpp
there is this subcribe/advertise code:
Imu_control::Imu_control(){

	body_cmd_sub = node.subscribe("/teleop/body_command", 1, &Imu_control::teleopBodyCmd, this);//No probado
	move_body_pub = node.advertise<spider_msgs::BodyState>("/teleop/move_body",1);//No probado
	pxf_imu_sub = node.subscribe("apm_inertial_sensor", 100, &Imu_control::imuCallback, this);
	ROS_INFO("Spider_imu_dev is ready...")

And on the header file: spider_imu_dev/src/Imu_control.hpp
		ros::Subscriber pxf_imu_sub;
		ros::Subscriber body_cmd_sub;
		ros::Publisher move_body_pub;

 I guess this code is still under development , but can you tell me if it would be possible to substitute the  pxf_imu publisher code with the ros_erle_imu/src/imu_talker.cpp ?
